"""The deterministic demo world: 200 incidents, 60 negatives, a held-out backtest set.

`build()` is a pure function of `(seed, anchor)` — same inputs, same world, down
to the last sample. That is what makes `make demo-reset` restore the exact state
the demo was rehearsed against, and what lets the backtest be re-run against a
world it was never fitted to.

The split matters: the backtest incidents and negatives are generated by the
same process as the seeded ones and then withheld entirely from the database.
Nothing about them reaches `precursor_snapshots`, so when Phase 7 runs Oracle
over them it is genuinely predicting windows the memory has never seen.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime, timedelta

import numpy as np

from nexus_common.trajectory import metric_digest, trajectory_text

from . import archetypes
from .trajectory import Trajectory, synthesize

DEFAULT_SEED = 20260819  # the submission date; any fixed value would do
HISTORY_DAYS = 90
N_INCIDENTS = 150
N_NEGATIVES = 47
N_HOLDOUT_INCIDENTS = 30
N_HOLDOUT_NEGATIVES = 12


@dataclass(frozen=True)
class Window:
    """One labelled telemetry window — an incident's precursor, or a negative."""

    key: str
    service: str
    region: str
    archetype: str
    led_to_incident: bool
    window_start: datetime
    window_end: datetime
    precursor_text: str
    digest: dict
    holdout: bool
    trajectory: Trajectory = field(repr=False)


@dataclass(frozen=True)
class Incident:
    key: str
    service: str
    region: str
    archetype: str
    title: str
    severity: int
    detected_at: datetime
    resolved_at: datetime
    mttr_seconds: int
    symptom_text: str
    was_predicted: bool
    was_prevented: bool
    was_auto_resolved: bool
    window: Window


@dataclass(frozen=True)
class World:
    seed: int
    anchor: datetime
    incidents: list[Incident]
    negatives: list[Window]

    @property
    def seeded_incidents(self) -> list[Incident]:
        return [i for i in self.incidents if not i.window.holdout]

    @property
    def seeded_negatives(self) -> list[Window]:
        return [w for w in self.negatives if not w.holdout]

    @property
    def backtest_incidents(self) -> list[Incident]:
        return [i for i in self.incidents if i.window.holdout]

    @property
    def backtest_negatives(self) -> list[Window]:
        return [w for w in self.negatives if w.holdout]


def _archetype_cycle(rng: np.random.Generator, count: int) -> list[archetypes.Archetype]:
    """Balanced-but-not-uniform archetype assignment: every archetype is well
    represented, with enough variation that the counts aren't suspiciously flat."""
    weights = np.array([1.35, 1.2, 1.0, 0.7, 0.9, 1.15, 1.0, 0.85])
    weights = weights / weights.sum()
    picks = rng.choice(len(archetypes.ARCHETYPES), size=count, p=weights)
    return [archetypes.ARCHETYPES[i] for i in picks]


def _window_for(
    traj: Trajectory, *, key: str, window_end: datetime, holdout: bool
) -> Window:
    metrics = traj.precursor_metrics()
    return Window(
        key=key,
        service=traj.service,
        region=traj.region,
        archetype=traj.archetype,
        led_to_incident=traj.led_to_incident,
        window_start=window_end - timedelta(minutes=traj.precursor_minutes),
        window_end=window_end,
        precursor_text=trajectory_text(
            service=traj.service,
            region=traj.region,
            window_minutes=traj.precursor_minutes,
            metrics=metrics,
            phase="precursor",
        ),
        digest={
            **metric_digest(metrics),
            "archetype": traj.archetype,
            "sample_interval_minutes": traj.sample_interval_minutes,
            "precursor_minutes": traj.precursor_minutes,
            "led_to_incident": traj.led_to_incident,
        },
        holdout=holdout,
        trajectory=traj,
    )


def build(*, seed: int = DEFAULT_SEED, anchor: datetime | None = None) -> World:
    """Generate the whole world. `anchor` is "now" — the end of simulated history."""
    anchor = (anchor or datetime.now(UTC)).replace(microsecond=0)
    rng = np.random.default_rng(seed)

    # Which indices are withheld from the database. Drawn before generation so
    # the split is stable regardless of how the records are later ordered.
    inc_holdout = set(
        int(i) for i in rng.choice(N_INCIDENTS, size=N_HOLDOUT_INCIDENTS, replace=False)
    )
    neg_holdout = set(
        int(i) for i in rng.choice(N_NEGATIVES, size=N_HOLDOUT_NEGATIVES, replace=False)
    )

    incidents: list[Incident] = []
    for idx, arch in enumerate(_archetype_cycle(rng, N_INCIDENTS)):
        service = str(rng.choice(arch.services or archetypes.SERVICES))
        region = str(rng.choice(archetypes.REGIONS))
        traj = synthesize(arch, rng=rng, service=service, region=region, led_to_incident=True)

        # Spread detection times over the simulated history, jittered within the day.
        day = float(rng.uniform(1.0, HISTORY_DAYS))
        detected_at = anchor - timedelta(days=day)
        mttr = int(rng.integers(240, 5400) * (1.0 + 0.12 * (arch.severity - 3)))
        # A minority of the historical incidents were caught by an earlier
        # generation of the system: that history is what the dashboard's
        # prevented-vs-impacted counters are drawn from.
        was_predicted = bool(rng.random() < 0.42)
        was_prevented = was_predicted and bool(rng.random() < 0.55)

        key = f"inc-{idx:04d}"
        incidents.append(
            Incident(
                key=key,
                service=service,
                region=region,
                archetype=arch.key,
                title=f"{arch.title} on {service} ({region})",
                severity=arch.severity,
                detected_at=detected_at,
                resolved_at=detected_at + timedelta(seconds=mttr),
                mttr_seconds=mttr,
                symptom_text=trajectory_text(
                    service=service,
                    region=region,
                    window_minutes=len(next(iter(traj.failure_metrics().values())))
                    * traj.sample_interval_minutes,
                    metrics=traj.failure_metrics(),
                    phase="failure",
                ),
                was_predicted=was_predicted,
                was_prevented=was_prevented,
                was_auto_resolved=was_prevented,
                window=_window_for(
                    traj, key=key, window_end=detected_at, holdout=idx in inc_holdout
                ),
            )
        )

    negatives: list[Window] = []
    for idx, arch in enumerate(_archetype_cycle(rng, N_NEGATIVES)):
        service = str(rng.choice(arch.services or archetypes.SERVICES))
        region = str(rng.choice(archetypes.REGIONS))
        traj = synthesize(arch, rng=rng, service=service, region=region, led_to_incident=False)
        observed_at = anchor - timedelta(days=float(rng.uniform(1.0, HISTORY_DAYS)))
        negatives.append(
            _window_for(
                traj,
                key=f"neg-{idx:04d}",
                window_end=observed_at,
                holdout=idx in neg_holdout,
            )
        )

    incidents.sort(key=lambda i: i.detected_at)
    negatives.sort(key=lambda w: w.window_end)
    return World(seed=seed, anchor=anchor, incidents=incidents, negatives=negatives)
